/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estadistica;

import Secuencial.BuscadorSecuencial;
import Secuencial.EstadisticaPalabra;
import Secuencial.Resultado;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Border;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import modelo.PaginasWeb;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author manfred
 */
public class VEstadistica extends javax.swing.JFrame {

    public ArrayList<Resultado> resultadosSecuencial;
    public ArrayList<EstadisticaPalabra> tiemposPalabrasSecuencial = new ArrayList<>();
    public BuscadorSecuencial buscador;

    /**
     * Creates new form VEstadistica
     */
    public VEstadistica() throws IOException {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IncidenciasB = new javax.swing.JButton();
        CPUB = new javax.swing.JButton();
        lienzo = new javax.swing.JPanel();
        pTablaSec = new javax.swing.JScrollPane();
        tablaIncidenciaSec = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IncidenciasB.setText("Incidencias");
        IncidenciasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncidenciasBActionPerformed(evt);
            }
        });

        CPUB.setText("CPU");

        lienzo.setBackground(new java.awt.Color(204, 204, 204));
        lienzo.setLayout(new java.awt.BorderLayout());

        tablaIncidenciaSec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incidencia", "Tiempo"
            }
        ));
        pTablaSec.setViewportView(tablaIncidenciaSec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTablaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IncidenciasB)
                    .addComponent(CPUB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(IncidenciasB)
                .addGap(18, 18, 18)
                .addComponent(CPUB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(pTablaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncidenciasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncidenciasBActionPerformed
        this.buscador = new BuscadorSecuencial();
        try {
            this.buscador.searchManager("vida | trabajo");
            this.resultadosSecuencial = buscador.resultados;
        } catch (IOException ex) {
            Logger.getLogger(VEstadistica.class.getName()).log(Level.SEVERE, null, ex);
        }
///Datos
        DefaultCategoryDataset barChartDatos = new DefaultCategoryDataset();
        barChartDatos.setValue(20000, "Contribuciones", "Enero");
        barChartDatos.setValue(30000, "Contribuciones", "Febrero");
        barChartDatos.setValue(40000, "Contribuciones", "Marzo");
        //fin datos
        
        this.tiemposPalabrasSecuencial = buscador.calcularTiempoPalabra("vida | trabajo", resultadosSecuencial);

        DefaultTableModel modeloTablaIncidencias = (DefaultTableModel) tablaIncidenciaSec.getModel();
        Object[] fila = new Object[modeloTablaIncidencias.getColumnCount()];
        for (EstadisticaPalabra palabra : tiemposPalabrasSecuencial) {
            fila[0] = palabra.getPalabra();
            fila[1] = palabra.getTiempo();
            modeloTablaIncidencias.addRow(fila);            
        }
//         Grafico
//        titulo-titulo arriba
        JFreeChart grafico = ChartFactory.createBarChart3D("Tiempos de ejecución", "Mensualmente", "Monto de las contribuciones", barChartDatos, PlotOrientation.VERTICAL, false, true, false);
        //

        CategoryPlot barChartCP = grafico.getCategoryPlot();
        barChartCP.setRangeGridlinePaint(Color.cyan);

        ChartPanel barPanel = new ChartPanel(grafico);
        lienzo.removeAll();
        lienzo.add(barPanel, BorderLayout.CENTER);
        lienzo.validate();

    }//GEN-LAST:event_IncidenciasBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VEstadistica().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VEstadistica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CPUB;
    private javax.swing.JButton IncidenciasB;
    private javax.swing.JPanel lienzo;
    private javax.swing.JScrollPane pTablaSec;
    private javax.swing.JTable tablaIncidenciaSec;
    // End of variables declaration//GEN-END:variables
}
